# Generated by Django 3.2 on 2022-11-13 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='default_street_address',
            new_name='default_street_address1',
        ),
    ]
