# Generated by Django 3.2 on 2022-07-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220717_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('friendly_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='harvest_times',
            field=models.ManyToManyField(related_name='products_to_harvest', to='products.Season'),
        ),
        migrations.AddField(
            model_name='product',
            name='sawing_times',
            field=models.ManyToManyField(related_name='products_to_saw', to='products.Season'),
        ),
    ]
