# Generated by Django 3.2 on 2022-07-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220718_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='friendly_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='season',
            name='friendly_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='friendly_name',
            field=models.CharField(max_length=100),
        ),
    ]
