# Generated by Django 3.2 on 2022-11-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_rating_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='indoors',
            field=models.BooleanField(default=False),
        ),
    ]
