# Generated by Django 3.2 on 2022-11-17 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_indoors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='harvest_times',
            field=models.ManyToManyField(blank=True, related_name='products_to_harvest', to='products.Season'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sawing_times',
            field=models.ManyToManyField(blank=True, related_name='products_to_saw', to='products.Season'),
        ),
    ]
